# Generated by Django 4.2 on 2026-03-20 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код спеціальності')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Назва роботи')),
                ('work_type', models.CharField(choices=[('qualification', 'Кваліфікаційна робота (дипломний проєкт)'), ('course', 'Курсова робота (проєкт)')], max_length=20, verbose_name='Тип роботи')),
                ('academic_year', models.CharField(help_text='Формат: 2024-2025', max_length=10, verbose_name='Навчальний рік')),
                ('defense_date', models.DateField(verbose_name='Дата захисту/подання')),
                ('pdf_file', models.FileField(upload_to='works/%Y/%m/', verbose_name='PDF файл роботи')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('approved', models.BooleanField(default=False, verbose_name='Схвалено модератором')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Коротка анотація')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works_as_author', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець (студент)')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.specialty', verbose_name='Спеціальність')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works_as_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Науковий керівник')),
            ],
            options={
                'verbose_name': 'Робота',
                'verbose_name_plural': 'Роботи',
                'ordering': ['-defense_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('admin', 'Адміністратор'), ('supervisor', 'Науковий керівник'), ('commission', 'Членом циклової комісії'), ('public', 'Загальнодоступно')], max_length=20, verbose_name='Рівень доступу')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата надання доступу')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='home.work', verbose_name='Робота')),
            ],
            options={
                'verbose_name': 'Доступ до роботи',
                'verbose_name_plural': 'Доступи до робіт',
                'unique_together': {('work', 'user', 'access_level')},
            },
        ),
        migrations.CreateModel(
            name='WorkDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=500, verbose_name='Назва роботи (архів)')),
                ('author_name', models.CharField(max_length=255, verbose_name='ПІБ виконавця (архів)')),
                ('deletion_date', models.DateField(auto_now_add=True, verbose_name='Дата видалення')),
                ('reason', models.TextField(verbose_name='Причина видалення')),
                ('deletion_act', models.FileField(blank=True, null=True, upload_to='deletion_acts/', verbose_name='Акт про вилучення')),
            ],
            options={
                'verbose_name': 'Видалена робота',
                'verbose_name_plural': 'Видалені роботи',
                'ordering': ['-deletion_date'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['-defense_date'], name='home_work_defense_7c6804_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['work_type'], name='home_work_work_ty_ca995a_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['specialty'], name='home_work_special_61db66_idx'),
        ),
    ]
