# Generated by Django 4.2 on 2026-03-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_specialty_work_workaccess_workdeletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('qualification_editor', 'Редактор кваліфікаційних робіт'), ('course_editor', 'Редактор курсових робіт'), ('viewer', 'Читач (перегляд PDF)')], default='viewer', max_length=30, verbose_name='Роль')),
                ('specialty', models.ForeignKey(blank=True, help_text='Заповнюється тільки для редактора кваліфікаційних робіт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.specialty', verbose_name='Спеціальність')),
                ('subject', models.ForeignKey(blank=True, help_text='Заповнюється тільки для редактора курсових робіт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject', verbose_name='Предмет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
