# Generated by Django 4.2 on 2026-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subject_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Виконавець (студент)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='supervisor',
            field=models.CharField(max_length=255, verbose_name='Науковий керівник'),
        ),
    ]
