# Generated by Django 4.2 on 2026-03-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_work_author_alter_work_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkAccess',
        ),
    ]
