# Generated by Django 4.2 on 2026-03-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_work_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='also_course_editor',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено, користувач (наприклад, Редактор КР) зможе також редагувати курсові роботи за вибраними предметами', verbose_name='Також є редактором курсових робіт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Для редактора курсових робіт або Читача: виберіть усі предмети, до яких дозволено доступ', related_name='editor_profiles', to='home.subject', verbose_name='Дозволені предмети'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, help_text='Заповнюється для редактора кваліфікаційних робіт або для обмеження Читача конкретною спеціальністю', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.specialty', verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Заповнюється для редактора курсових робіт (як основний)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject', verbose_name='Предмет (основний)'),
        ),
    ]
