# Generated by Django 4.2 on 2026-03-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_also_course_editor_userprofile_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='home.specialty', verbose_name='Спеціальність'),
        ),
    ]
